#FROM specified which image i want to download
# Needs to be provided before any other section of code.
FROM tomcat

#Author of the Docker File
MAINTAINER Pictolearn

# Copy the following directory
COPY spring-mvc-docker-sample.war /opt/tomcat/webapps/ROOT.war