#FROM specified which image i want to download
# Needs to be provided before any other section of code.
FROM tomcat

#Author of the Docker File
MAINTAINER Pictolearn

# Copy the following directory
#COPY pictolearn-sample/ /usr/share/nginx/html/pictolearn 